version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://dna-community-back.onrender.com
    networks:
      - dna-network
    command: npm run dev

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=dna_community_dev
      - POSTGRES_USER=dna_user
      - POSTGRES_PASSWORD=dna_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dna-network

volumes:
  postgres_dev_data:

networks:
  dna-network:
    driver: bridge